// 18 Tour Recommendations — structured from Section-09 Action Matrix + Business Case
// Markets: US UK CA AU NZ IE ZA · SG IN PH
// Categories: food, adventure, cultural, wellness, package, nature

export const MARKET_FLAGS = {
  US: "🇺🇸", UK: "🇬🇧", CA: "🇨🇦", AU: "🇦🇺", NZ: "🇳🇿",
  IE: "🇮🇪", ZA: "🇿🇦", SG: "🇸🇬", IN: "🇮🇳", PH: "🇵🇭",
};

export const CATEGORY_COLORS = {
  food:      "#FB923C", // orange
  adventure: "#22C55E", // green
  cultural:  "#A78BFA", // purple
  wellness:  "#F472B6", // pink
  package:   "#38BDF8", // accent
  nature:    "#06B6D4", // cyan
};

export const CATEGORY_LABELS = {
  food:      "🍜 Food",
  adventure: "⛰️ Adventure",
  cultural:  "🏛️ Cultural",
  wellness:  "🧘 Wellness",
  package:   "📦 Package",
  nature:    "🌿 Nature",
};

// Month pills — color hint by season
export const MONTH_COLOR = {
  May: "#22C55E", Jun: "#22C55E", Jul: "#FB923C",
  Aug: "#FB923C", Sep: "#38BDF8", Oct: "#38BDF8",
};

export const TOURS = [
  {
    id: 1,
    name: "Half-Day Hanoi Street Food Tour (Morning)",
    shortName: "Hanoi Street Food",
    category: "food",
    route: "Old Quarter: Dong Xuan Market → Hang Buom craft beer alley → Bia Hoi Corner → Train Street photo stop → Egg Coffee at Giang Cafe → Bun Cha Huong Lien",
    duration: "4h · 8:30am",
    markets: ["US", "UK", "AU", "CA"],
    platforms: ["Viator", "GYG"],
    bestMonths: ["Jun", "Jul", "Aug"],
    bestMonthsLabel: "Jun–Aug",
    priceRange: "$35–55 mid / $70–120 private",
    revenue: "$350–550 (≤10 khách)",
    rationale: "S2: food tours #1 category, immune to wet season (covered markets). S8: US/UK/AU summer peak Jul-Aug. S5: small group ≤10 + local guide + 10-12 tastings = \"sweet spot combo\" (4.8★+). Hanoi mornings dry even in wet season, avoid Jul-Aug afternoon heat (37°C).",
    whyInvest: "Food tours = hạng mục số 1 trên OTA. Top 5 nhà điều hành tại Hà Nội nắm giữ ~60% lượng booking với review moat 3,000–5,000+ mỗi listing. Khoảng trống: ngách \"chợ sáng + bia thủ công + cà phê trứng\" chưa ai chiếm — cơ hội vượt review moat bằng niche angle.",
    competitors: "Real Foodie (4,794+ reviews Viator, 4.9★) · Hanoi Street Food Tour (3,200+ reviews GYG)",
    barrier: "Cao — review moat cần 200+ đánh giá. Giải pháp: định dạng ngách khác biệt hoàn toàn.",
  },
  {
    id: 2,
    name: "Evening Saigon Street Food & Craft Beer Scooter Tour",
    shortName: "Saigon Scooter Food",
    category: "food",
    route: "HCMC District 1: Ben Thanh → District 4 (banh mi, hu tieu) → Bui Vien → District 3 craft beer → Nguyen Hue Walking Street",
    duration: "4h · 5:30pm",
    markets: ["AU", "UK", "US"],
    platforms: ["Viator", "Airbnb Experiences"],
    bestMonths: ["Jun", "Jul", "Aug"],
    bestMonthsLabel: "Jun–Aug",
    priceRange: "$50–80 mid",
    revenue: "$500–800 (≤10 khách)",
    rationale: "S2: nightlife/after-dark = emerging format. S6: XO Tours (all-female) proved model với 4.94 Airbnb. S8: HCMC year-round, afternoon rain clears by 5pm. S1: AU Adventure Seekers + UK younger 25-40 = primary.",
    whyInvest: "XO Tours đã chứng minh với 100K+ khách, Top 9 Forbes — nhưng KHÔNG niêm yết trên Klook. Khoảng trống = kênh Klook cho SG/AU/IN + friendly cho khách nam + nhóm 25–40.",
    competitors: "XO Tours (Airbnb, all-female model)",
    barrier: "XO có brand moat trên Airbnb; Klook là làn đường trống, chưa có ai chiếm lĩnh.",
  },
  {
    id: 3,
    name: "Full-Day Hoi An Cooking Class + Basket Boat + Ancient Town",
    shortName: "Hoi An Cooking Combo",
    category: "food",
    route: "Tra Que herb village → local market shopping → hands-on cooking (4 dishes) → basket boat Cam Thanh → Ancient Town + lantern workshop",
    duration: "8h · 8am",
    markets: ["US", "UK", "CA", "AU"],
    platforms: ["Viator", "GYG"],
    bestMonths: ["May", "Jun", "Jul", "Aug"],
    bestMonthsLabel: "May–Aug",
    priceRange: "$65–100 combo",
    revenue: "$650–1,000 (≤10 khách)",
    rationale: "S2: cooking classes #2, food tours #1 — bundles both. S3: Central Coast DRY season May-Aug = BEST. S7: food + cooking = highest-traction bundle. S5: hands-on = #3 success factor. S8: time around Hoi An Full Moon nights.",
    whyInvest: "Các lớp nấu ăn đạt TB 600+ reviews/listing trên Viator; 100+ standalone trên Cookly. Khoảng trống = combo nấu ăn + thuyền thúng + phố cổ trong 8h KHÔNG phổ biến — tạo giá trị \"3-in-1\".",
    competitors: "VM Travel Hoi An (2,500+ reviews TripAdvisor) · Hoi An Eco Tour",
    barrier: "Trung bình — lớp nấu ăn đơn lẻ bão hòa; combo ít cạnh tranh hơn.",
  },
  {
    id: 4,
    name: "3-Day Ha Giang Loop by Jeep (Non-Rider Friendly)",
    shortName: "Ha Giang Jeep",
    category: "adventure",
    route: "Hanoi pickup → Ha Giang city → Quan Ba Heaven Gate → Dong Van karst → Ma Pi Leng Pass → Lung Cu Flag Tower → Du Gia homestay → Hanoi",
    duration: "3D2N",
    markets: ["AU", "UK", "US"],
    platforms: ["Viator", "TripAdvisor"],
    bestMonths: ["Jul", "Aug", "Sep"],
    bestMonthsLabel: "Jul–Sep",
    priceRange: "$160–300 (3D2N mid)",
    revenue: "$480–900 (≥3 khách)",
    rationale: "S2: Ha Giang = breakout star, TikTok viral. S3: rice terraces GREEN PEAK May-Sep, GOLDEN Sep-Oct. S1: Adventure Seeker persona (AU/UK). S6: fragmented supply = opportunity. S3: jeep mở market ngoài motorbike riders (solo female, 35+).",
    whyInvest: "20+ nhà điều hành OTA nhưng KHÔNG có thương hiệu dẫn dắt — phân mảnh = cơ hội first-mover. Jeep mở rộng thị trường ngoài motorbike riders. TikTok viral đang đẩy nhu cầu tăng vọt.",
    competitors: "Ha Giang Motor Ventures · hostel-affiliated operators (không có brand mạnh)",
    barrier: "Thấp — không có thương hiệu dẫn dắt. Cần đối tác Jeep tại Ha Giang + chuẩn hóa 3D2N.",
  },
  {
    id: 5,
    name: "Full-Day Cu Chi Tunnels + Mekong Delta VIP Combo",
    shortName: "Cu Chi + Mekong VIP",
    category: "cultural",
    route: "HCMC → Cu Chi Tunnels (small group) → lunch at local Mekong home → Ben Tre coconut village sampan → honey tea + fruit tasting → Vinh Trang Pagoda",
    duration: "10h · 7:30am",
    markets: ["US", "UK", "AU", "IN"],
    platforms: ["Viator", "GYG", "Klook"],
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    bestMonthsLabel: "Jun–Sep",
    priceRange: "$65–90 full-day",
    revenue: "$650–900 (≤10 khách)",
    rationale: "S2: Cu Chi + Mekong = #4 category, stable demand. S3: Mekong BETTER in wet season (water rising Jul-Oct). S5: all-inclusive + local home meal = top factors. S1: IN family groups appreciate comprehensive package.",
    whyInvest: "Thường xuyên top 20 VN trên Viator. \"Hai điểm trong 1 ngày\" = giá trị cảm nhận cao. Điểm đau #1 = xe lớn 30-40 khách — VIP nhóm nhỏ là đòn phản công với giá chỉ cao 20-30%.",
    competitors: "Saigon Adventure · Joy Journeys (2,000+ reviews Viator)",
    barrier: "Trung bình — hạng mục đã chín; differentiate bằng group size cap + home meal (không dừng shopping).",
  },
  {
    id: 6,
    name: "2-Day Ninh Binh \"Ha Long Bay on Land\" + Homestay",
    shortName: "Ninh Binh Homestay",
    category: "nature",
    route: "Hanoi → Trang An boat (UNESCO) → Tam Coc rice paddies cycling → Mua Cave sunset → rural homestay → Bich Dong Pagoda → Hanoi",
    duration: "2D1N",
    markets: ["US", "UK", "AU", "NZ"],
    platforms: ["Viator", "GYG", "Airbnb Experiences"],
    bestMonths: ["May", "Jun"],
    bestMonthsLabel: "May–Jun",
    priceRange: "$160–220 (2D1N mid)",
    revenue: "$160–220/khách",
    rationale: "S3: Ninh Binh = \"established alternative\" to Ha Long, closer to Hanoi (100km vs 170km), less crowded. S8: May-Jun = BEST (rice green, pre-heavy rain). S2: slow travel + homestay emerging. S1: Culture-Hungry Explorers.",
    whyInvest: "Positioning \"Hạ Long trên cạn\" = SEO demand sẵn. Gần Hà Nội hơn, ít đông đúc -40%. TripAdvisor Trending 2025-2026. Đối thủ chỉ có day-tour — 2D1N là khoảng trống lớn.",
    competitors: "Nhiều nhà điều hành Hà Nội (chỉ có day-tour format)",
    barrier: "Thấp đến trung bình — Ninh Binh có sẵn homestay hạ tầng; 2D combo ít cạnh tranh.",
  },
  {
    id: 7,
    name: "5-Day Central Vietnam Festival Trail (Hue–Da Nang–Hoi An)",
    shortName: "Central VN Festival",
    category: "cultural",
    route: "Hue: Imperial Citadel + Thien Mu + Hue Festival → Hai Van Pass → Da Nang: DIFF Fireworks + My Khe → Hoi An: Ancient Town + cooking + Full Moon lantern",
    duration: "5D4N",
    markets: ["US", "UK", "CA", "AU"],
    platforms: ["Viator", "TourRadar", "GYG"],
    bestMonths: ["May", "Jun", "Jul"],
    bestMonthsLabel: "May–Jul",
    priceRange: "$400–650 (5D4N mid)",
    revenue: "$400–650/khách",
    rationale: "S8: DIFF fireworks May 30-Jul 11, Hue Festival summer, Hoi An Full Moon monthly. S3: Hoi An-Hue Hai Van Pass = top route #4. S8: Central Coast DRY May-Aug. S1: Culture-Hungry Explorers prefer 7-14 days, 5-day core block.",
    whyInvest: "3 điểm nhấn lịch trình đồng thời (DIFF + Hue Festival + Full Moon) = đỉnh nhu cầu dự đoán được. Tháng 7 = US/CA/AU/UK ĐỀU peak cùng lúc — cửa sổ hiếm hoi.",
    competitors: "Intrepid Travel · TourRadar multi-day packages",
    barrier: "Trung bình — hậu cần đa ngày cần mạng đối tác dọc miền Trung; cao hơn tour đơn tỉnh.",
  },
  {
    id: 8,
    name: "Half-Day Da Nang Beach + Golden Bridge (Ba Na Hills) Combo",
    shortName: "Da Nang + Ba Na",
    category: "package",
    route: "Da Nang hotel → Ba Na Hills cable car → Golden Bridge → French Village → Fantasy Park → My Khe Beach sunset",
    duration: "8h · 8am",
    markets: ["SG", "IN", "PH"],
    platforms: ["Klook", "Traveloka"],
    bestMonths: ["Jun", "Jul", "Aug"],
    bestMonthsLabel: "Jun–Aug",
    priceRange: "$55–80 full-day",
    revenue: "$550–800 (≤10 khách)",
    rationale: "S2: Ba Na Hills #9 category, strong Asian market pull. S4: Klook dominates SG/IN/PH. S1: Asian Weekend Escaper — SG (3-5 day), IN (family). S8: SG June holiday peak. S3: Da Nang short-haul from SG (2.5h).",
    whyInvest: "Top 10 VN trên Klook; lực hút mạnh SG/IN/PH. Mệt mỏi với điểm đến Instagram ở phương Tây — nhưng Asian short-break (SG June, IN National Day) vẫn peak. Distribution play thuần trên Asian platforms.",
    competitors: "Nhiều operators trên Klook/Traveloka (volume cao, differentiation thấp)",
    barrier: "Trung bình-cao — Ba Na Hills đã commodity; differentiate bằng experience packaging + small group.",
  },
  {
    id: 9,
    name: "3-Day Singapore School Holiday Getaway (HCMC Focus)",
    shortName: "SG Holiday HCMC",
    category: "package",
    route: "SG → HCMC (2h15): Day 1 evening food tour → Day 2 Cu Chi + spa → Day 3 Mekong half-day → evening flight",
    duration: "3D2N package",
    markets: ["SG"],
    platforms: ["Klook", "Traveloka"],
    bestMonths: ["Jun", "Sep"],
    bestMonthsLabel: "Jun, Sep",
    priceRange: "$220–350 (3D2N)",
    revenue: "$220–350/khách",
    rationale: "S1: SG = Asian Weekend Escaper, 3-5 day, mobile-first, last-minute. S8: SG June holiday (May 30-Jun 28) = PRIMARY peak, Sep secondary. S4: Klook instant confirmation + flash sales. S3: HCMC shortest flight from SG.",
    whyInvest: "SG hè (30/5-28/6) = đỉnh 4 tuần dự đoán được. SG = 900K khách, 2h15 flight, miễn visa. Instant confirm Klook = SG booking behavior. Chưa có gói HCMC 3D2N dành riêng SG trên Klook.",
    competitors: "Nhiều day-tour HCMC (không có 3D2N dedicated SG)",
    barrier: "Thấp — đóng gói tour HCMC hiện có + niêm yết Klook focus SG holiday timing.",
  },
  {
    id: 10,
    name: "India Family Group Hanoi–Ha Long Bay Package (Veg-Friendly, 4–8 pax)",
    shortName: "India Family Ha Long",
    category: "package",
    route: "Hanoi: Old Quarter + vegetarian pho + Water Puppet → Ha Long Bay: day cruise (kayaking, cave, veg lunch, Ti Top) → Hanoi night market",
    duration: "3D2N",
    markets: ["IN"],
    platforms: ["Klook", "Viator"],
    bestMonths: ["May", "Jun"],
    bestMonthsLabel: "May–Jun",
    priceRange: "$220–350 (3D2N)",
    revenue: "$220–350/khách",
    rationale: "S1: India = +49% YoY, #1 growth market, family/group, veg-friendly MUST-HAVE. S6: Indian market adaptation = supply gap #7. S7: Indian family adaptation = quick win #2. S8: India summer holiday May-Jun = PRIMARY. S4: Klook primary for IN.",
    whyInvest: "746K khách IN 2025, +49% YoY — thị trường nguồn tăng trưởng nhanh nhất. Supply gap #7: CHƯA CÓ tour OTA tối ưu cho gia đình IN (veg, giá nhóm 4-8, Klook priority, Hindi docs). 100 chuyến thẳng/tuần.",
    competitors: "KHÔNG có operator dẫn dắt cho IN-adapted tours trên OTA",
    barrier: "Rất thấp — adapt tour hiện có: thêm veg + giá nhóm + Klook. ROI cao nhất mỗi nỗ lực.",
  },
  {
    id: 11,
    name: "2-Day Sapa Rice Terrace Trek + Hmong Homestay",
    shortName: "Sapa Trek Homestay",
    category: "adventure",
    route: "Hanoi overnight → Sapa → Cat Cat Village → Lao Chai trek → Ta Van Hmong homestay (home dinner) → rice terrace walk → Fansipan cable car → Hanoi",
    duration: "2D1N",
    markets: ["AU", "UK", "NZ", "CA"],
    platforms: ["Viator", "GYG"],
    bestMonths: ["Jun", "Jul", "Sep", "Oct"],
    bestMonthsLabel: "Jun–Jul, Sep–Oct",
    priceRange: "$160–300 (2D1N mid)",
    revenue: "$160–300/khách",
    rationale: "S3: Sapa trekking = route #6, homestay trending. S8: Jun-Jul = green rice peak, Sep-Oct = golden harvest (best scenery). S1: Adventure Seeker (AU/UK). S6: Sapa Sisters (Hmong-led) = identity model. S5: authentic + small group ≤8.",
    whyInvest: "Tuyến đi bộ Sapa = #6, homestay trending. Sep-Oct golden harvest = visual peak. Sapa Sisters đã chứng minh mô hình Hmong-led — authentic connection = emotional impact cao nhất trong reviews.",
    competitors: "Sapa Sisters (Hmong-led, unique USP) · generic operators",
    barrier: "Thấp-TB — cần Hmong guide partner. Identity-led model khó sao chép.",
  },
  {
    id: 12,
    name: "Half-Day Hoi An Wellness Retreat (Yoga + Herbal Bath + Mindful Lunch)",
    shortName: "Hoi An Wellness",
    category: "wellness",
    route: "Hoi An: sunrise yoga at riverside pavilion → Tra Que herb garden → herbal bath + Vietnamese massage → farm-to-table veg lunch → meditation",
    duration: "5h · 6am",
    markets: ["US", "UK", "AU", "SG"],
    platforms: ["Viator", "Airbnb Experiences", "Klook"],
    bestMonths: ["May", "Jun", "Jul", "Aug"],
    bestMonthsLabel: "May–Aug",
    priceRange: "$80–150 mid (day retreat)",
    revenue: "$800–1,500 (≤10 khách)",
    rationale: "S6: wellness = supply gap #1 (projected $11.7B by 2033, <20 listings on Viator/GYG). S7: mid-range wellness day retreat = whitespace opportunity #4. S3: Central Coast DRY May-Aug. S2: wellness emerging, government-backed.",
    whyInvest: "Khoảng trống lớn nhất trên OTA: <20 wellness listings trên Viator/GYG vs dự báo $11.7B by 2033. Day retreat mid-range ($80-150) = hoàn toàn trống. Chưa có đối thủ trực tiếp — vị thế first-mover.",
    competitors: "KHÔNG có đối thủ trực tiếp ở định dạng mid-range day retreat trên OTA",
    barrier: "Cạnh tranh thấp; cần yoga instructor + spa partner + location Hoi An. Test Airbnb Experiences trước.",
  },
  {
    id: 13,
    name: "Full-Day Phong Nha Cave Adventure (Dark Cave + Paradise Cave)",
    shortName: "Phong Nha Caves",
    category: "adventure",
    route: "Dong Hoi → Phong Nha-Ke Bang NP: Paradise Cave (limestone cathedral) → Dark Cave (kayak + zip-line + mud bath + swimming) → local lunch → Botanical Garden",
    duration: "8h · 7:30am",
    markets: ["AU", "UK", "US"],
    platforms: ["Viator", "GYG"],
    bestMonths: ["May", "Jun", "Jul"],
    bestMonthsLabel: "May–Jul",
    priceRange: "$65–100 full-day",
    revenue: "$650–1,000 (≤10 khách)",
    rationale: "S3: Phong Nha = rain-proof adventure, growing listings. S8: May-Jul = best window before Aug heavy rain. S6: supply gap #2 — thin OTA presence despite strong demand. S2: adventure + canyoneering trending. S1: Adventure Seekers (AU/UK).",
    whyInvest: "Oxalis gần như độc quyền cave cao cấp, full trước nhiều tháng. Khoảng trống = mid-tier: Dark + Paradise không cần rope cert — dễ tiếp cận mass traveler. UNESCO heritage đang tăng độ phủ truyền thông.",
    competitors: "Oxalis Adventure Tours (cao cấp, $200+/khách, rào cản cao)",
    barrier: "Thấp trên OTA — supply mỏng vs demand tăng. Đòn bẩy: địa lý (Dong Hoi airport access).",
  },
  {
    id: 14,
    name: "3-Day Quy Nhon Coastal Discovery (Beach + Cham Ruins + Seafood)",
    shortName: "Quy Nhon Coastal",
    category: "nature",
    route: "Quy Nhon airport → Ky Co Beach (snorkeling, cliff jumping) → Eo Gio cliff → Nhon Ly fishing village (seafood) → Thap Doi + Thap Banh It Cham Towers → Bai Xep sunset",
    duration: "3D2N",
    markets: ["AU", "UK", "US"],
    platforms: ["Viator", "GYG"],
    bestMonths: ["May", "Jun", "Jul", "Aug"],
    bestMonthsLabel: "May–Aug",
    priceRange: "$200–350 (3D2N mid)",
    revenue: "$200–350/khách",
    rationale: "S3: Quy Nhon = Lonely Planet Best in Travel 2026, TripAdvisor Trending #4 globally, National Tourism Year 2026. S7: first-mover advantage, low OTA supply vs high demand signal. S8: dry season May-Aug. Bottleneck = limited flights (5h bus from Da Nang).",
    whyInvest: "3 chất xúc tác đồng thời: Lonely Planet Best in Travel 2026 + TripAdvisor Trending #4 + National Tourism Year 2026. OTA supply rất thấp vs search signal tăng. First-mover advantage còn nguyên.",
    competitors: "KHÔNG có operator OTA dẫn dắt tại Quy Nhon",
    barrier: "Rất thấp — first-mover tại emerging destination với 3 bảo chứng lớn 2026.",
  },
  {
    id: 15,
    name: "Half-Day Mekong Delta Floating Market + Coconut Village (Sunrise)",
    shortName: "Mekong Floating Market",
    category: "nature",
    route: "HCMC → Can Tho overnight (or 4am) → Cai Rang Floating Market sunrise → fruit orchard → coconut candy workshop → sampan ride → local lunch",
    duration: "6h core · 4am",
    markets: ["US", "UK", "AU", "IN"],
    platforms: ["Viator", "GYG", "Klook"],
    bestMonths: ["Jul", "Aug", "Sep", "Oct"],
    bestMonthsLabel: "Jul–Oct",
    priceRange: "$45–70 full-day",
    revenue: "$450–700 (≤10 khách)",
    rationale: "S3: Mekong Delta = #2 route, wet season = SCENIC PEAK (water rising, floating markets busiest). S8: Jul-Oct = Mekong flood = BEST time. S2: boat + sampan tours = #7 category, UP. S5: hands-on coconut candy + sunrise = photo-worthy + fewer crowds.",
    whyInvest: "Mekong = route #2 VN. Mùa nước nổi Jul-Oct = chợ nổi nhộn nhịp nhất (activity peak). Sunrise 4am = differentiator ngược dòng: ít crowd + golden hour photos.",
    competitors: "Joy Journeys (2,000+ reviews) · Saigon Adventure (standard 9am departure)",
    barrier: "Thấp — differentiate qua sunrise timing + coconut candy workshop (hands-on S5 #3).",
  },
  {
    id: 16,
    name: "Evening Hanoi Craft Beer + Night Food Walking Tour",
    shortName: "Hanoi Night Food",
    category: "food",
    route: "Hanoi: Bia Hoi Junction → Ta Hien \"Beer Street\" → hidden pho spot → Train Street (timed with train) → Dong Xuan Night Market → rooftop egg coffee",
    duration: "3.5h · 6pm",
    markets: ["AU", "UK", "US", "CA"],
    platforms: ["Viator", "GYG", "Airbnb Experiences"],
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    bestMonthsLabel: "Jun–Sep",
    priceRange: "$30–50 evening",
    revenue: "$300–500 (≤10 khách)",
    rationale: "S2: night tours + food = stable demand, evening avoids rain (afternoon rain → evening clear). S8: Hanoi Jul-Aug very hot — evening = weather workaround. S2: nightlife = emerging. S5: small group ≤10 + hidden spots = off-beaten-path.",
    whyInvest: "Evening format giải quyết nắng nóng Hà Nội Jul-Aug (37°C ban ngày) — UK peak tháng 8 cần option evening. Beer + food = social format, thúc đẩy group booking. Night tours ít cạnh tranh hơn day tours.",
    competitors: "Nhiều night tour Hà Nội (phân mảnh, không có brand dẫn dắt)",
    barrier: "Thấp — guide + route; list Viator + Airbnb Experiences. Triển khai nhanh.",
  },
  {
    id: 17,
    name: "Full-Day Dalat Canyoneering + Waterfall Adventure",
    shortName: "Dalat Canyoneering",
    category: "adventure",
    route: "Da Lat: hotel pickup → Datanla Falls (rappelling, cliff jumping, water slides, zip-line) → lunch → Elephant Falls trek → Crazy House → Langbiang sunset",
    duration: "8h · 8am",
    markets: ["AU", "UK", "US"],
    platforms: ["Klook", "Viator"],
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    bestMonthsLabel: "Jun–Sep",
    priceRange: "$60–90 full-day",
    revenue: "$600–900 (≤10 khách)",
    rationale: "S2: canyoneering Dalat = trending on Klook. S8: wet season = MORE water = BETTER canyoneering. S3: Central Highlands 18-24°C = cool escape when lowlands 35-40°C. S1: AU/UK Adventure Seekers. Unique format not replicable in VN.",
    whyInvest: "Wet season = nhiều nước hơn = canyoneering tốt hơn — positioning ngược dòng nhưng chính xác, differentiate mạnh. Dalat 18-24°C = trốn nóng khi đồng bằng 35-40°C. Format không replicate được nơi khác tại VN.",
    competitors: "Nhiều adventure operators Đà Lạt (canyoneering growing, Klook distribution)",
    barrier: "Thấp-TB — cần local guide cert + safety equipment.",
  },
  {
    id: 18,
    name: "Philippines Barkada Group HCMC Weekend (4–6 pax, 4D3N)",
    shortName: "PH Barkada HCMC",
    category: "package",
    route: "MNL → HCMC (3h): Day 1 evening Bui Vien + street food → Day 2 Cu Chi + spa → Day 3 Mekong + Ben Thanh → Day 4 brunch + departure",
    duration: "4D3N",
    markets: ["PH"],
    platforms: ["Klook", "Traveloka"],
    bestMonths: ["May", "Jun"],
    bestMonthsLabel: "May–Jun, year-round",
    priceRange: "$280–450 (4D3N)",
    revenue: "$280–450/khách",
    rationale: "S1: PH = +81% YoY, 482K arrivals, ASEAN visa-free, 3h flight, barkada (friend group) travel pattern. S8: PH summer break May-mid Jun. S4: Klook/Traveloka primary. S1: Asian Weekend Escaper, mobile-first, budget-to-mid. S3: HCMC hub = closest major from MNL.",
    whyInvest: "PH = +81% YoY, 482K khách. Miễn visa ASEAN, 3h flight. Barkada model = natural 4-6 pax package. Klook = nền tảng chính PH. Chưa có HCMC 4D3N dedicated PH market trên OTA.",
    competitors: "KHÔNG có operator dẫn dắt nhắm PH identified",
    barrier: "Rất thấp — đóng gói tour HCMC hiện có + barkada pricing + Klook SG/PH listing.",
  },
];
